export const PageTheme = {
  colors: {
    primary: "#0CEBBB",
    secondary: "#17142C",
    black: "#000000",
    white: "#FFFFFF"
  },
  borderRadius: {
    roundedNone: "0px",
    roundedSM: "2px",
    rounded: "4px",
    roundedMD: "6px",
    roundedLG: "8px",
    roundedXL: "12px",
    rounded2XL: "16px",
    rounded3xl: "24px",
    rounded4xl: "86px",
    roundedFull: "100%",
  },
  spacing: {
    spacing4: "4px",
    spacing8: "8px",
    spacing12: "12px",
    spacing16: "16px",
    spacing24: "24px",
    spacing32: "32px",
    spacing48: "48px",
    spacing64: "64px",
    spacing96: "96px",
    spacing128: "128px",
    spacing192: "192px",
    spacing256: "256px",
  },
  breakpoints: {
    width: {
      mobileS: `all and (min-width:320px)`,
      mobileM: `all and (min-width:375px)`,
      mobileL: `all and (min-width:425px)`,
      tablet: `all and (min-width:768px)`,
      laptopS: `all and (min-width:968px)`,
      laptop: `all and (min-width:1024px)`,
      desktopS: `all and (min-width:1200px)`,
      desktopM: `all and (min-width:1440px)`,
      desktopL: `all and (min-width:1920px)`,
      desktop4K: `all and (min-width:2500px)`,
    },
    height: {
      mobileSH: `all and (min-height:320px)`,
      mobileMH: `all and (min-height:375px)`,
      mobileLH: `all and (min-height:425px)`,
      tabletH: `all and (min-height:768px)`,
      laptopSH: `all and (min-height:968px)`,
      laptopH: `all and (min-height:1024px)`,
      desktopSH: `all and (min-height:1200px)`,
      desktopMH: `all and (min-height:1440px)`,
      desktopLH: `all and (min-height:1920px)`,
      desktop4KH: `all and (min-height:2500px)`,
    },
  },
};
